apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/pv/db-claim1  # Replace with your desired host path
