apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    io.kompose.service: db
spec:
  selector:
    io.kompose.service: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
