services:
  db:
    container_name: homeflix_db
    image: mariadb:11.4.2-ubi9
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=homeflix
      - MYSQL_DATABASE=homeflix
      - MYSQL_USER=homeflix
      - MYSQL_PASSWORD=homeflix
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/populate.sql
      - db-data:/var/lib/mysql

  php:
    container_name : homeflix_php
    image: rg.fr-par.scw.cloud/namespace-hungry-sanderson/homeflix-php-cloud:latest
    restart: always

  web:
    container_name: homeflix_web
    image: rg.fr-par.scw.cloud/namespace-hungry-sanderson/homeflix-web-cloud:latest
    ports:
      - "8008:80"
    depends_on:
      - php
      - db

volumes:
  db-data:
