apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-configmap
data:
  data.sql: |
    CREATE TABLE `accounts` (
      `id_account` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `firstname` VARCHAR(50) NOT NULL,
      `lastname` VARCHAR(50) NOT NULL,
      `birth` DATE NOT NULL,
      `gender` ENUM("men", "women", "other"),
      `id_country` INT NOT NULL,
      `email` VARCHAR(100) NOT NULL,
      `billing` VARCHAR(100) NOT NULL,
      `password` VARCHAR(50) NOT NULL,
      PRIMARY KEY(`id_account`)
    );
    CREATE INDEX `index_0`
    ON `accounts` (`id_account`);

    CREATE TABLE `profils` (
      `id_profil` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_account` INT NOT NULL,
      `avatar` VARCHAR(100) NOT NULL,
      `creation` DATE,
      `pseudo` VARCHAR(30) NOT NULL,
      `type` ENUM("child", "adult") NOT NULL,
      `id_language` INT,
      PRIMARY KEY(`id_profil`)
    );
    CREATE INDEX `index_1`
    ON `profils` (`id_profil`);

    CREATE TABLE `video_file` (
      `id_video_file` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `file_name` VARCHAR(30) NOT NULL,
      `id_shop` INT,
      `id_file_transcription` INT NOT NULL,
      `id_obj` INT NOT NULL,
      PRIMARY KEY(`id_video_file`)
    );
    CREATE INDEX `index_2`
    ON `video_file` (`id_video_file`);

    CREATE TABLE `countries` (
      `id_country` INT NOT NULL,
      `name` VARCHAR(50) NOT NULL UNIQUE,
      `code` VARCHAR(2) NOT NULL,
      PRIMARY KEY(`id_country`)
    );
    CREATE INDEX `index_3`
    ON `countries` (`id_country`);

    CREATE TABLE `productions` (
      `id_production` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255) NOT NULL,
      `id_country` INT NOT NULL,
      `id_obj` INT NOT NULL,
      PRIMARY KEY(`id_production`)
    );
    CREATE INDEX `index_4`
    ON `productions` (`id_production`);

    CREATE TABLE `songs` (
      `id_song` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `songtitle` VARCHAR(255) NOT NULL,
      `year` INT NOT NULL,
      PRIMARY KEY(`id_song`)
    );
    CREATE INDEX `index_5`
    ON `songs` (`id_song`);

    CREATE TABLE `shops` (
      `id_shop` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `url` VARCHAR(255) NOT NULL,
      PRIMARY KEY(`id_shop`)
    );
    CREATE INDEX `index_6`
    ON `shops` (`id_shop`);

    CREATE TABLE `types_objet` (
      `id_type_obj` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255) NOT NULL,
      PRIMARY KEY(`id_type_obj`)
    );
    CREATE INDEX `index_7`
    ON `types_objet` (`id_type_obj`);

    CREATE TABLE `objects` (
      `id_obj` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_type_obj` INT NOT NULL,
      `id_genre` INT,
      `name` VARCHAR(255) NOT NULL,
      PRIMARY KEY(`id_obj`)
    );
    CREATE INDEX `index_8`
    ON `objects` (`id_obj`);

    CREATE TABLE `asso_objects` (
      `id_asso_obj` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_obj_parent` INT NOT NULL,
      `id_obj_enfant` INT NOT NULL,
      PRIMARY KEY(`id_asso_obj`)
    );
    CREATE INDEX `index_9`
    ON `asso_objects` (`id_asso_obj`);

    CREATE TABLE `type_roles` (
      `id_role` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255) NOT NULL,
      PRIMARY KEY(`id_role`)
    );
    CREATE INDEX `index_10`
    ON `type_roles` (`id_role`);

    CREATE TABLE `people` (
      `id_people` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255) NOT NULL,
      `id_country` INT NOT NULL,
      PRIMARY KEY(`id_people`)
    );
    CREATE INDEX `index_11`
    ON `people` (`id_people`);

    CREATE TABLE `asso_objects_participants_roles` (
      `id_asso` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_obj` INT,
      `id_role` INT,
      `id_people` INT,
      PRIMARY KEY(`id_asso`)
    );
    CREATE INDEX `index_12`
    ON `asso_objects_participants_roles` (`id_asso`);

    CREATE TABLE `genres` (
      `id_genre` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255),
      PRIMARY KEY(`id_genre`)
    );
    CREATE INDEX `index_13`
    ON `genres` (`id_genre`);

    CREATE TABLE `asso_genres_objects` (
      `id_asso` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_genre` INT NOT NULL,
      `id_obj` INT NOT NULL,
      PRIMARY KEY(`id_asso`)
    );
    CREATE INDEX `index_14`
    ON `asso_genres_objects` (`id_asso`);

    CREATE TABLE `types_transcriptions` (
      `id_type_transcription` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255) NOT NULL,
      PRIMARY KEY(`id_type_transcription`)
    );
    CREATE INDEX `index_15`
    ON `types_transcriptions` (`id_type_transcription`);

    CREATE TABLE `tech_languages` (
      `id_tech_language` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_type_transcription` INT NOT NULL,
      `id_language` INT NOT NULL,
      PRIMARY KEY(`id_tech_language`)
    );
    CREATE INDEX `index_16`
    ON `tech_languages` (`id_tech_language`);

    CREATE TABLE `languages` (
      `id_language` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255),
      PRIMARY KEY(`id_language`)
    );
    CREATE INDEX `index_17`
    ON `languages` (`id_language`);

    CREATE TABLE `qualities` (
      `id_quality` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `name` VARCHAR(255) NOT NULL,
      PRIMARY KEY(`id_quality`)
    );
    CREATE INDEX `index_18`
    ON `qualities` (`id_quality`);

    CREATE TABLE `tech_qualities` (
      `id_tech_quality` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_quality` INT,
      `id_type_transcription` INT,
      PRIMARY KEY(`id_tech_quality`)
    );
    CREATE INDEX `index_19`
    ON `tech_qualities` (`id_tech_quality`);

    CREATE TABLE `files_transcriptions` (
      `id_file_transcription` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_tech_quality` INT NOT NULL,
      `id_tech_language` INT NOT NULL,
      PRIMARY KEY(`id_file_transcription`)
    );
    CREATE INDEX `index_20`
    ON `files_transcriptions` (`id_file_transcription`);

    CREATE TABLE `asso_objects_songs` (
      `id_asso` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_obj` INT NOT NULL,
      `id_song` INT,
      PRIMARY KEY(`id_asso`)
    );
    CREATE INDEX `index_21`
    ON `asso_objects_songs` (`id_asso`);

    CREATE TABLE `asso_people_songs` (
      `id_asso` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_people` INT,
      `id_song` INT,
      PRIMARY KEY(`id_asso`)
    );
    CREATE INDEX `index_22`
    ON `asso_people_songs` (`id_asso`);

    CREATE TABLE `asso_productions_people` (
      `id_asso` INT NOT NULL AUTO_INCREMENT UNIQUE,
      `id_production` INT NOT NULL,
      `id_people` INT NOT NULL,
      PRIMARY KEY(`id_asso`)
    );
    CREATE INDEX `index_23`
    ON `asso_productions_people` (`id_asso`);

    ALTER TABLE `profils`
    ADD FOREIGN KEY(`id_account`) REFERENCES `accounts`(`id_account`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `accounts`
    ADD FOREIGN KEY(`id_country`) REFERENCES `countries`(`id_country`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `objects`
    ADD FOREIGN KEY(`id_type_obj`) REFERENCES `types_objet`(`id_type_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_objects`
    ADD FOREIGN KEY(`id_obj_parent`) REFERENCES `objects`(`id_type_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_objects`
    ADD FOREIGN KEY(`id_obj_enfant`) REFERENCES `objects`(`id_type_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_objects_participants_roles`
    ADD FOREIGN KEY(`id_obj`) REFERENCES `objects`(`id_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_objects_participants_roles`
    ADD FOREIGN KEY(`id_role`) REFERENCES `type_roles`(`id_role`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_objects_participants_roles`
    ADD FOREIGN KEY(`id_people`) REFERENCES `people`(`id_people`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_genres_objects`
    ADD FOREIGN KEY(`id_obj`) REFERENCES `objects`(`id_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_genres_objects`
    ADD FOREIGN KEY(`id_genre`) REFERENCES `genres`(`id_genre`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `tech_languages`
    ADD FOREIGN KEY(`id_language`) REFERENCES `languages`(`id_language`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `tech_languages`
    ADD FOREIGN KEY(`id_type_transcription`) REFERENCES `types_transcriptions`(`id_type_transcription`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `tech_qualities`
    ADD FOREIGN KEY(`id_type_transcription`) REFERENCES `types_transcriptions`(`id_type_transcription`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `tech_qualities`
    ADD FOREIGN KEY(`id_quality`) REFERENCES `qualities`(`id_quality`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `video_file`
    ADD FOREIGN KEY(`id_shop`) REFERENCES `shops`(`id_shop`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `files_transcriptions`
    ADD FOREIGN KEY(`id_tech_language`) REFERENCES `tech_languages`(`id_tech_language`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `files_transcriptions`
    ADD FOREIGN KEY(`id_tech_quality`) REFERENCES `tech_qualities`(`id_tech_quality`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `video_file`
    ADD FOREIGN KEY(`id_file_transcription`) REFERENCES `files_transcriptions`(`id_file_transcription`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `video_file`
    ADD FOREIGN KEY(`id_obj`) REFERENCES `objects`(`id_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_objects_songs`
    ADD FOREIGN KEY(`id_song`) REFERENCES `songs`(`id_song`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_objects_songs`
    ADD FOREIGN KEY(`id_obj`) REFERENCES `objects`(`id_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_people_songs`
    ADD FOREIGN KEY(`id_people`) REFERENCES `people`(`id_people`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_people_songs`
    ADD FOREIGN KEY(`id_song`) REFERENCES `songs`(`id_song`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `profils`
    ADD FOREIGN KEY(`id_language`) REFERENCES `languages`(`id_language`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_productions_people`
    ADD FOREIGN KEY(`id_production`) REFERENCES `productions`(`id_production`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `asso_productions_people`
    ADD FOREIGN KEY(`id_people`) REFERENCES `people`(`id_people`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `productions`
    ADD FOREIGN KEY(`id_country`) REFERENCES `countries`(`id_country`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;
    ALTER TABLE `productions`
    ADD FOREIGN KEY(`id_obj`) REFERENCES `objects`(`id_obj`)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

  populate.sql: |
    -- Populate countries table
    INSERT INTO `countries` (`id_country`, `name`, `code`) VALUES
    (1, 'United States', 'US'),
    (2, 'Canada', 'CA'),
    (3, 'United Kingdom', 'UK'),
    (4, 'Australia', 'AU'),
    (5, 'Germany', 'DE');

    -- Populate accounts table
    INSERT INTO `accounts` (`firstname`, `lastname`, `birth`, `gender`, `id_country`, `email`, `billing`, `password`) VALUES
    ('Kaci', 'Dupont', '1985-06-15', 'women', 1, 'kaci@homeflix', '123 Main St, Anytown, USA', 'motdepasse'),
    ('Dylan', 'Michel', '1990-08-20', 'women', 2, 'dylan@homeflix', '456 Elm St, Othertown, Canada', 'pouetpouet69'),
    ('Hicham', 'Cloud', '1975-12-05', 'men', 3, 'hicham@homeflix', '789 Oak St, Sometown, UK', 'motdepasse2');

    -- Populate languages table
    INSERT INTO `languages` (`name`) VALUES
    ('English'),
    ('French'),
    ('German'),
    ('Spanish');

    -- Populate profiles table
    INSERT INTO `profils` (`id_account`, `avatar`, `creation`, `pseudo`, `type`, `id_language`) VALUES
    (1, 'https://100k-faces.glitch.me/random-image', '2023-01-01', 'Kaci', 'adult', 1),
    (2, 'https://100k-faces.glitch.me/random-image', '2023-02-01', 'janey', 'adult', 2),
    (3, 'https://100k-faces.glitch.me/random-image', '2023-03-01', 'alice', 'adult', 1);

    -- Populate types_objet table
    INSERT INTO `types_objet` (`name`) VALUES
    ('Movie'),
    ('TV Show'),
    ('Documentary');

    -- Populate objects table
    INSERT INTO `objects` (`id_type_obj`, `id_genre`, `name`) VALUES
    (1, NULL, 'Inception'),
    (2, NULL, 'Breaking Bad'),
    (3, NULL, 'Planet Earth');

    -- Populate genres table
    INSERT INTO `genres` (`name`) VALUES
    ('Action'),
    ('Drama'),
    ('Sci-Fi'),
    ('Nature');

    -- Populate asso_genres_objects table
    INSERT INTO `asso_genres_objects` (`id_genre`, `id_obj`) VALUES
    (1, 1),
    (3, 1),
    (2, 2),
    (4, 3);

    -- Populate type_roles table
    INSERT INTO `type_roles` (`name`) VALUES
    ('Director'),
    ('Actor'),
    ('Producer');

    -- Populate people table
    INSERT INTO `people` (`name`, `id_country`) VALUES
    ('Christopher Nolan', 1),
    ('Bryan Cranston', 2),
    ('David Attenborough', 3);

    -- Populate asso_objects_participants_roles table
    INSERT INTO `asso_objects_participants_roles` (`id_obj`, `id_role`, `id_people`) VALUES
    (1, 1, 1),
    (2, 2, 2),
    (3, 3, 3);

    -- Populate productions table
    INSERT INTO `productions` (`name`, `id_country`, `id_obj`) VALUES
    ('Warner Bros', 1, 1),
    ('AMC', 2, 2),
    ('BBC', 3, 3);

    -- Populate asso_productions_people table
    INSERT INTO `asso_productions_people` (`id_production`, `id_people`) VALUES
    (1, 1),
    (2, 2),
    (3, 3);

    -- Populate shops table
    INSERT INTO `shops` (`url`) VALUES
    ('https://example.com/shop1'),
    ('https://example.com/shop2');

    -- Populate songs table
    INSERT INTO `songs` (`songtitle`, `year`) VALUES
    ('Song A', 2010),
    ('Song B', 2015);

    -- Populate asso_objects_songs table
    INSERT INTO `asso_objects_songs` (`id_obj`, `id_song`) VALUES
    (1, 1),
    (2, 2);

    -- Populate asso_people_songs table
    INSERT INTO `asso_people_songs` (`id_people`, `id_song`) VALUES
    (1, 1),
    (2, 2);

    -- Populate qualities table
    INSERT INTO `qualities` (`name`) VALUES
    ('HD'),
    ('SD');

    -- Populate types_transcriptions table
    INSERT INTO `types_transcriptions` (`name`) VALUES
    ('Subtitle'),
    ('Dub');

    -- Populate tech_languages table
    INSERT INTO `tech_languages` (`id_type_transcription`, `id_language`) VALUES
    (1, 1),
    (2, 2);

    -- Populate tech_qualities table
    INSERT INTO `tech_qualities` (`id_quality`, `id_type_transcription`) VALUES
    (1, 1),
    (2, 2);

    -- Populate files_transcriptions table
    INSERT INTO `files_transcriptions` (`id_tech_language`, `id_tech_quality`) VALUES
    (1, 1),
    (2, 2);

    -- Populate video_file table
    INSERT INTO `video_file` (`file_name`, `id_shop`, `id_file_transcription`, `id_obj`) VALUES
    ('video1.mp4', 1, 1, 1),
    ('video2.mp4', 2, 2, 2);

    -- Populate asso_objects table
    INSERT INTO `asso_objects` (`id_obj_parent`, `id_obj_enfant`) VALUES
    (1, 2),
    (2, 3);

    -- Insert two new movies
    INSERT INTO `objects` (`id_type_obj`, `id_genre`, `name`) VALUES
    (1, NULL, 'The Matrix'),
    (1, NULL, 'Interstellar');

    -- Insert genres for the new movies
    INSERT INTO `asso_genres_objects` (`id_genre`, `id_obj`) VALUES
    (1, (SELECT id_obj FROM objects WHERE name='The Matrix')),
    (2, (SELECT id_obj FROM objects WHERE name='Interstellar'));

    -- Insert productions for the new movies
    INSERT INTO `productions` (`name`, `id_country`, `id_obj`) VALUES
    ('Warner Bros', 1, (SELECT id_obj FROM objects WHERE name='The Matrix')),
    ('Paramount Pictures', 1, (SELECT id_obj FROM objects WHERE name='Interstellar'));

    -- Insert video files for the new movies
    INSERT INTO `video_file` (`file_name`, `id_shop`, `id_file_transcription`, `id_obj`) VALUES
    ('matrix.mp4', 1, 1, (SELECT id_obj FROM objects WHERE name='The Matrix')),
    ('interstellar.mp4', 1, 1, (SELECT id_obj FROM objects WHERE name='Interstellar'));

    -- Insert One Piece episode
    INSERT INTO `objects` (`id_type_obj`, `id_genre`, `name`) VALUES
    (2, NULL, 'One Piece Episode 1');

    -- Insert genres for One Piece episode
    INSERT INTO `asso_genres_objects` (`id_genre`, `id_obj`) VALUES
    (2, (SELECT id_obj FROM objects WHERE name='One Piece Episode 1'));

    -- Insert productions for One Piece episode
    INSERT INTO `productions` (`name`, `id_country`, `id_obj`) VALUES
    ('Toei Animation', 1, (SELECT id_obj FROM objects WHERE name='One Piece Episode 1'));

    -- Insert video file for One Piece episode
    INSERT INTO `video_file` (`file_name`, `id_shop`, `id_file_transcription`, `id_obj`) VALUES
    ('one_piece_ep1.mp4', 1, 1, (SELECT id_obj FROM objects WHERE name='One Piece Episode 1'));

    -- Insert Naruto episode
    INSERT INTO `objects` (`id_type_obj`, `id_genre`, `name`) VALUES
    (2, NULL, 'Naruto: The Cross Roads');

    -- Insert genres for Naruto episode
    INSERT INTO `asso_genres_objects` (`id_genre`, `id_obj`) VALUES
    (2, (SELECT id_obj FROM objects WHERE name='Naruto: The Cross Roads'));

    -- Insert productions for Naruto episode
    INSERT INTO `productions` (`name`, `id_country`, `id_obj`) VALUES
    ('Pierrot', 1, (SELECT id_obj FROM objects WHERE name='Naruto: The Cross Roads'));

    -- Insert video file for Naruto episode
    INSERT INTO `video_file` (`file_name`, `id_shop`, `id_file_transcription`, `id_obj`) VALUES
    ('naruto_ep1.mp4', 1, 1, (SELECT id_obj FROM objects WHERE name='Naruto: The Cross Roads'));
