apiVersion: v1
kind: Service
metadata:
  name: homeflix-php
  labels:
    io.kompose.service: php
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: php
