apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    io.kompose.service: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  template:
    metadata:
      labels:
        io.kompose.service: php
    spec:
      containers:
        - name: homeflix-php
          image: rg.fr-par.scw.cloud/namespace-hungry-sanderson/homeflix-php-cloud:latest
          ports:
            - containerPort: 9000
