apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/homeflix-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: nginx:1.27.0-alpine
          name: homeflix-web
          ports:
            - containerPort: 80
              hostPort: 8008
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: web-claim0
            - mountPath: /etc/nginx/conf.d/default.conf
              name: web-claim1
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
        - name: web-claim1
          persistentVolumeClaim:
            claimName: web-claim1
